### ISSUE TITLE
Kubectl tests.

### ISSUE THREAD

**Issue by timothysc** [heptio/kube-conformance#19]
Upstream test were broken for a while on kubectl tests that were run in-cluster. 

There were a number of changes to fix this and we should evaluate and update the skip-list.

/cc @chuckha @liztio

**Comment by spiffxp** [comment]
I'd like to discuss this at tomorrow cncf-conformance-wg meeting.  The Kubectl tests should not be skipped.

**Comment by johnSchnake** [comment]
These are no longer skipped; closing.
