### ISSUE TITLE
Track upstream releases better

### ISSUE THREAD

**Issue by chuckha** [heptio/kube-conformance#25]
Since releasing is manual, we track the first few release of k8s and then assume the conformance tests are not changing for the release. We need to track our v1.x tags with release-1.x upstream.

**Comment by timothysc** [comment]
We need to move kube-conformance upstream and have that be part of the release artifacts of upstream imo.  We've carried this debt for too long.

**Comment by johnSchnake** [comment]
The kube-conformance image is now maintained upstream so this issue should get closed once we start to use it. As of now it hasn't been released yet so we are holding off on that being the default.

xref #4

**Comment by johnSchnake** [comment]
Going to close this since the upstream will start using this. We should have a small # of releases left.
