### ISSUE TITLE
Need the files of 'CONTRIBUTING.md' & 'LICENSE'

### ISSUE THREAD

**Issue by lubinsz** [heptio/kube-conformance#27]
Hi,
I'm from ARM. We need to enable this project to support multi-arch.
I have fixed the same issue in sonobuoy. Please see:
https://github.com/heptio/sonobuoy/pull/491

But our legal department need to check the policy for contribution & license.
I can't find the files of 'CONTRIBUTING.md' & 'LICENSE'

For your reference:
https://github.com/heptio/sonobuoy/blob/master/CONTRIBUTING.md
https://github.com/heptio/sonobuoy/blob/master/LICENSE

**Comment by lubinsz** [comment]
@chuckha @liztio 
Can you check it?
Thanks.

**Comment by chuckha** [comment]
@lubinsz I'm confused about what you're asking for. Are you looking for https://github.com/heptio/kube-conformance/blob/master/LICENSE ? I can add a contributing.md file, we should have had that already.
